


SUPPORTED_SENSOR_TYPES += ACCELEROMETER



SUPPORTED_DRIVERS += ACCELEROMETER_ICM20648


$(NAME)_DRIVER_ACCELEROMETER_ICM20648_REQUIRED_COMPONENTS  := $(COMPONENTS_ROOT).drivers.accelerometers.icm20648

